clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 5

steps:
  init-secrets:
    when:
      - event: push
    image: infisical/cli
    environment:
      INFISICAL_TOKEN:
        from_secret: VAULT_TOKEN
    commands:
      - infisical export --domain https://vault.devforth.io/api --format=dotenv-export --env="prod" > /woodpecker/deploy.vault.env

  build:
    image: node:20
    when:
      - event: push
    commands:
      - apt update && apt install -y rsync
      - set -a
      - source /woodpecker/deploy.vault.env
      - set +a
      - npm clean-install
      - /bin/bash ./.woodpecker/buildRelease.sh
      - npm audit signatures

  release:
    image: node:20
    when:
      - event: push
        branch: main
    commands:
      - set -a
      - source /woodpecker/deploy.vault.env
      - set +a
      - npx semantic-release

  slack:
    image: curlimages/curl
    when:
      - event: push
        status: [success, failure]
    commands:
      - |
        if [ ! -f /woodpecker/deploy.vault.env ]; then
          echo "No env file, skipping slack notify"
          exit 0
        fi
      - set -a
      - source /woodpecker/deploy.vault.env
      - set +a
      - /bin/sh ./.woodpecker/buildSlackNotify.sh
